pages/login.html

issue  #11 
I have created the login page using HTML and Bootstrap. It is a responsive page as I have used bootstrap. Here are some pictures of the web page.
<br>
1)
<br>
2)
<br>
3)
<br>
4)
<br>
5)

Added Login page

---

index.html
styles/styles.css

Hey @IAmTamal  I did everything that was asked
Changed the text to Uppercase,
made the font size bigger, 
made the keywords bolder,
improved the text style and gave a text-shadow so the text stands out a bit more
I also gave it a media query since the bigger font size was breaking it at smaller screen size 
Also, the buttons were looking unsymmetrical so to make them look symmetrical I gave a width to the smaller one
BEFORE
AFTER

Banner text #14  

---

index.html
milan/form.css
milan/form.html

closes #8 
Hi, again @IAmTamal !!
I have added the Registration Form and linked it with the "Register" button.
- The "Sign Up" button will turn green when the user will hover over it.
- The home icon will redirect the user to the main page.

Added Registration Form

---

contact us/con-styles.css
contact us/contact-styles.css
contact us/contact.html
contact us/contact_us.html

Issue : #10 
made a responsive contact page.

contact us page made

---

milan-app/src/App.jsx
milan-app/src/components/Banner.jsx
milan-app/src/components/SingleClub.jsx
milan-app/src/pages/display/CLUB_DATA.js
milan-app/src/pages/display/ClubsPage.css
milan-app/src/pages/display/ClubsPage.jsx

Closes #33 
1) Added Link for navigation to `/display/clubs`  
2) `SingleClub.jsx`: Bootstrap card to show each card  
3) Converted Data to JavaScript file and mapped each object to SingleClub  
4) **Final outcome**
5) Added Read More- Read Less buttons for each card
6) Additional styling of scrollbar for all pages

Clubs And Clubs Page

---

milan-app/src/pages/user/UserRegister.jsx
milan-app/src/styles/UserRegister.css

This PR fixes issue #47.
Closes: #47.
Guidelines 🔐
**Changes -**
Updates UI according to user login page `milan-app/src/pages/user/UserLogin.jsx`
Files changed:
- `milan-app/src/pages/user/UserRegister.jsx`
- `milan-app/src/styles/UserRegister.css`
**Screenshots -**

Updated UI for user registration page according to user login page

---

milan-app/package-lock.json
milan-app/src/components/Footer.jsx
milan-app/src/pages/Home.jsx
milan-app/src/styles/Footer.css

JWOC participant
Closes #44 
I have created this footer component using react

Adding the footer component

---

milan-app/src/styles/ContactUs.css

Jwoc participant
Closes https://github.com/IAmTamal/Milan/issues/55
Dekstop view
:
it is responsive. & i have added the changes u asked for,

UI/UX - Styles fix

---

server/models/ClubsSchema.js

<h3>Issue no: #66  </h3>
Closes #66

ClubsSchema is created in server/models

---

server/routes/Display.js

Show all clubs

---

milan-app/src/styles/Footer.css

Fixes: #87 
Before Fixing -
After Fixed -

Fixed: Position of Report button in footer

---

milan-app/src/pages/ContactUs.jsx
milan-app/src/styles/ContactUs.css

This PR adds feature #93.
Closes: #93
Updates:
`/milan-app/src/pages/ContactUs.jsx`: Added navbar component and a 'Return Home' button
`/milan-app/src/styles/ContactUs.css`: Added styles for 'Return Home' button
**Screenshots:**

Added header and return home link

---

milan-app/src/styles/AboutUs.css

Closes #94 
I fixed the font-styling on the about page.
Preview:

#94 Fixed font-style on about page

---

server/routes/User.js

Backend for user login

---

milan-app/src/pages/user/UserLogin.jsx
milan-app/src/pages/user/UserRegister.jsx
milan-app/src/service/MilanApi.js
milan-app/src/styles/UserLogin.css

This PR adds new feature for #103.
Closes: #103
**Fixed warnings :**
fixed keywords that caused warnings and labels for inputs with dummy tags
- `/milan-app/src/pages/user/UserLogin.jsx`
- `/milan-app/src/pages/user/UserRegister.jsx`
- `/milan-app/src/styles/UserLogin.css`
**Added new features:**
- `/milan-app/src/service/MilanApi.js` : Added backend integration for user registration
- `/milan-app/src/pages/user/UserRegister.jsx` : Added function call for user registration and route to login page
https://user-images.githubusercontent.com/56752104/154745203-7f28e278-e4a7-4eb1-9a5a-45048bc6606c.mp4

Fixed errors in user display and state and added backend integration for user registration

---

milan-app/src/pages/clubs/ClubsRegister.jsx
milan-app/src/service/MilanApi.js
server/routes/Clubs.js

This PR adds new feature for #102.
Closes: https://github.com/IAmTamal/Milan/issues/102
**Fixed warnings :**
fixed keywords that caused warnings and labels for inputs with dummy tags
- `/milan-app/src/pages/user/ClubRegister.jsx`
Added new features:
- `/milan-app/src/service/MilanApi.js` : Added backend integration for club registration
- `/server/routes/Clubs.js` : Fixed a spelling error on response object
https://user-images.githubusercontent.com/56752104/154752860-2a7b4171-16e2-4b46-975b-28e7fbc7f1aa.mp4

Fixed bugs in club register form and state and added backend integration for club registration 

---

milan-app/package-lock.json
milan-app/package.json
milan-app/src/pages/user/UserLogin.jsx
milan-app/src/service/MilanApi.js
server/package-lock.json
server/routes/User.js

Fixes: #101 
Screenshot-
Postman- 
Entering correct details -
Entering wrong Password -
Entering wrong email and password which doesn't exists -

Connected the user's login frontend to backend

---

.github/workflows/release.yml
milan-app/package-lock.json
milan-app/package.json

feat: added semantic

---

.github/workflows/release.yml
milan-app/src/styles/AboutUs.css

fix: updated styles

---

milan-app/src/components/DonateBanner.jsx
milan-app/src/components/Events.jsx
milan-app/src/styles/DonateBanner.css
milan-app/src/styles/Events.css

- **I <your name here> have worked for this issue under JWOC**
- **My pull request closes #105**
Added some extra contributions while working on these issues in the last 2 days :
- Also fixed responsiveness of donate-banner section on home page in #105
- Fixed form inputs, labels and states in user registration components in #103
- Fixed form inputs, labels and states in club registration components in #102 
---

Fix picture and content size for event section in home page

---

milan-app/src/pages/clubs/ClubsLogin.jsx
milan-app/src/service/MilanApi.js
server/routes/Clubs.js

Fixes: #100 
Postman(For club register)-
On entering details which does not exists-
On entering wrong password- 
On entering correct details-
It will redirect to the home page

Connected the club's login frontend to backend

---

rules/Setup.md

fix: Updated server setup.

---

CONTRIBUTING.md
rules/Setup.md

I updated guidelines for setups, contributions

fix: updated guidelines for setups, contributions

---

CHANGELOG.md
package-lock.json
package.json
server/models/ReportProblemSchema.js
server/routes/User.js

- **I Kushal Ghosh has worked for this issue under JWOC**
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet** 
- My pull request closes #123 
**Here are the pictures of changes that I have made⤵**
---

fix: Added Report API backend route with DB model

---

CHANGELOG.md
CONTRIBUTING.md
package-lock.json
package.json
server/models/ReportProblemSchema.js
server/routes/Clubs.js
server/routes/Display.js
server/routes/User.js
src/components/Events.jsx
src/components/Footer.jsx
src/components/Navbar.jsx
src/pages/ContactUs.jsx
src/pages/clubs/ClubsLogin.jsx
src/pages/user/UserLogin.jsx
src/pages/user/UserRegister.jsx

Here are the changes that were made to the deployed version of code : 
- removed extra vars, comments
- Fixed "path" bugs
- Fixed unreachable codes
- Backend API for reports

fix: Refactored code

---

actTEST.md

fix: updates 1

---

src/styles/ContactUs.css

- **I Tejaswi have worked for this issue under JWOC**
- **My pull request closes  #111 **
https://user-images.githubusercontent.com/72697074/154832381-6f0826dd-09ca-48cc-b27a-e70208bfe8d6.mp4
---

fix: Contact us layout

---

actTEST.md

I have added the workflows so that the releases are drafted and notes are tracked accordingly 
- Update Version (0)

feat: Introduced workflows

---

.github/release-drafter.yml
actTEST.md

feat: Version resolver

---

package-lock.json
src/components/Footer.jsx
src/styles/Footer.css

- **I Mridul Dey have worked for this issue under JWOC**
- **My pull request closes #112 **
https://user-images.githubusercontent.com/56752104/154839216-4e2026ec-a1e4-4ba2-aac6-bbbe2fe427ce.mp4
---

fix: updated footer responsiveness for all screens

---

.github/release-drafter.yml

feat: updated version resolver to labels

---

src/components/SingleClub.jsx
src/pages/display/ClubsPage.jsx
src/service/MilanApi.js
src/styles/ClubsPage.css

- **I Mridul Dey have worked for this issue under JWOC**
- **My pull request closes #145**
---

feat: added backend integration for fetching all clubs

---

server/.gitignore
server/package-lock.json
src/service/MilanApi.js
src/styles/ClubsPage.css

- backend deployed to heroku
- font styles fixed

feat: Deployed backend

---

package-lock.json
src/components/Footer.jsx
src/service/MilanApi.js
src/styles/Footer.css

- **I Daksh Gupta have worked for this issue under JWOC**
- **My pull request closes #144**
#UI of the modal as per the figma modal  
---

fix: Updated report integration and added Report Modal

---

src/components/Footer.jsx
src/styles/Footer.css

- **I Manjot Singh Oberoi have worked for this issue under JWOC**
- **My pull request closes #151 **
---

fix: Report Modal glitches out

---

src/styles/Banner.css

- **I Mridul Dey have worked for this issue under JWOC**
- **My pull request closes #152 **
---

fix: resized buttons for smaller devices

---

src/components/loginBanner.jsx
src/styles/LoginBanner.css

- **I Tejaswi have worked for this issue under JWOC**
- **My pull request closes #158 **
https://user-images.githubusercontent.com/72697074/155844079-b7661596-392a-43d8-990c-efe470ebc4dd.mp4
---

fix: image sizing

---

src/pages/Home.jsx
src/pages/user/UserLogin.jsx
src/styles/LoginBanner.css

fixed file names

---

src/styles/LoginBanner.css

- **I Tejaswi have worked for this issue under JWOC**
- **My pull request closes #162 **
Screen size: 393 x 851
---

fix: Resized font on smaller screens

---

server/models/EventsSchema.js

- **I Munagapati yeshwanth have worked for this issue under JWOC**
- **My pull request closes #169*
---

events schema is added in server/model

---

src/pages/clubs/ClubsLogin.jsx
src/styles/ClubLogin.css

- **I Mridul Dey have worked for this issue under JWOC**
- **My pull request closes #173 **
---

fix: resized club login form for mobiles

---

package-lock.json
package.json
src/pages/clubs/ClubsRegister.jsx
src/styles/ClubsRegister.css

- **I Tejaswi have worked for this issue under JWOC**
- **My pull request closes #174 **
https://user-images.githubusercontent.com/72697074/156320001-994d788e-c2cc-4e52-acfb-8776549de96b.mp4
---

fix: Club section changes

---

server/models/ContactUsSchema.js
server/routes/User.js

- **I [r3yc0n1c](https://github.com/r3yc0n1c) have worked for this issue under JWOC**
- My pull request closes #182 
**Here are the pictures of changes that I have made⤵**
---

fix: Created contactUsSchema and a new route

---

README.md

- None just saw some things I could change quickly
It's a simple README fix without changing any visual elements.
---

Fix grammar and wording in README.md

---

package-lock.json
package.json
src/components/DonateBanner.jsx
src/components/Events.jsx
src/styles/DonateBanner.css
src/styles/Events.css

- **I <your name here> have added explore icon and hover effect in the donation and event jsx and css files**
- **My pull request closes #207 **
---

UI/UX Improvements - Homepage sections 

---

package-lock.json
server/db.js
src/service/MilanApi.js

- **My pull request closes #209 **

Added routes , ready for deploy C1

---

src/components/Footer.jsx

- **I Adithya Udayan have worked for #211**
- **My pull request closes #211 **
---

Fix : Anchor tags 🛠

---

server/package-lock.json
src/components/Events.jsx
src/components/Footer.jsx
src/pages/display/EventsPage.jsx

- **I Rinshin Jalal have worked for Issue of Events Page#215 **
- **My pull request closes #215 **
[Screencast from 07-12-2022 03:07:59 PM.webm](https://user-images.githubusercontent.com/88965873/178460465-58b999f7-42e9-4f29-abbf-92db37531994.webm)
---

Fixed : Issue of Events Page

---

src/components/Footer.jsx
src/styles/Footer.css

- **I Rohit Roy, have worked for #214**
- **My pull request closes #214**
---

Fixed the footer bugs !

---

src/components/Footer.jsx
src/pages/clubs/ClubsLogin.jsx
src/pages/user/UserLogin.jsx
src/styles/Footer.css

- **I, Rohit Roy have worked for #216 **
- **My pull request closes #216 **
ClubLogin Page > 
UserLogin Page > 
---

Fixed differences b/w UserLogin & ClubLogin page ! 

---

src/pages/clubs/ClubsLogin.jsx
src/styles/ClubLogin.css

- **I Rohit Roy have worked for #223 **
- **My pull request closes #223 **
---

Fixed LOGIN button bug on Club Login page !

---

src/components/loginBanner.jsx
src/styles/LoginBanner.css

- **I Rohit Roy have worked for #226 **
- **My pull request closes #226 **
100% view > 
50% view > 
150% vew > 
---

Fixed UserLogin Welcome Page !

---

public/index.html
server/routes/Clubs.js
src/components/Navbar.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/user/UserRegister.jsx
src/service/MilanApi.js
src/styles/ClubsRegister.css
src/styles/UserLogin.css

- Brand new formats for Registration,Login Screen.
- Made the images more optimized
- Removed the Navbar extra logo

Added new formats (Reg,Login)

---

src/components/SingleEvent.jsx
src/pages/clubs/EventCreate.jsx
src/service/MilanApi.js

- Changes made to Single events.
- Changes made to API to post event.
- Changes made for conditional rendering.

Events related change

---

src/pages/display/EventsPage.jsx
src/styles/ClubsPage.css

- **I, Kristi Ingco, have worked for #237 **
- **My pull request closes #237  *
Event Page on Pixel 5
Event Page on iPhone SE
Event Page on iPad Air (portrait and landscape)
---

Fix Mobile Responsiveness in Event Page

---

package-lock.json
package.json
src/components/SingleClub.jsx
src/pages/Donate.jsx
src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/display/CLUB_DATA.js
src/pages/user/UserLogin.jsx
src/pages/user/UserRegister.jsx
src/service/MilanApi.js

- Added toastify
- Added toasts to most of the events that are utilized by clients
- Fixed some minor bugs regarding"error" toasts

Added toasts

---

src/components/Footer.jsx
src/components/SocialIcons.jsx
src/styles/Footer.css

- **I, Kristi Ingco, have worked for 236 *
- **My pull request closes #236 **
Footer for Samsung Galaxy S20 Ultra
Footer for iPhone SE 
Footer for Pixel 5
---

fix: Modify mobile styling for footer

---

server/index.js
server/package-lock.json
server/package.json
server/routes/Payment.js
src/components/SingleClub.jsx
src/pages/Donate.jsx
src/pages/display/EventsPage.jsx
src/service/PaymentGateway.js

Added donations using razorpay ✅

---

src/pages/display/EventsPage.jsx
src/styles/ClubsPage.css

- **I <your name here> have worked for #254**
- **My pull request closes #254**
Donate Page > 
Evant Page > 
---

Fixed banner differences [Donate/Event] page

---

package-lock.json
src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/user/UserLogin.jsx

- **I Dunsin have worked for #269 **
- **My pull request closes #269 **
---

fix: add placeholder text to input forms

---

src/pages/user/UserRegister.jsx

- **I Roei have worked for #273 **
- **My pull request closes #273 **
---

Remove forget password from the user register page

---

src/pages/display/EventsPage.jsx
src/styles/ClubsPage.css

- **I <your name here> have worked for #276 **
- **My pull request closes #276 **
Mobile view:
Tablet view:
---

Fix: Event page responsiveness

---

README.md
package-lock.json

- **I @Dun-sin have worked for #280 **
- **My pull request closes #280 **
---

docs: fix broken link and add proper tech stack

---

src/components/Banner.jsx
src/components/DonateBanner.jsx
src/components/Footer.jsx
src/pages/ContactUs.jsx
src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/user/UserLogin.jsx
src/pages/user/UserRegister.jsx
src/service/PaymentGateway.js
src/styles/Banner.css

- **I  have worked for #285**
- **My pull request closes #285**

Accessibility focusmanagement

---

src/components/Footer.jsx
src/styles/DonateBanner.css
src/styles/EventCreate.css
src/styles/Events.css
src/styles/Footer.css
src/styles/HomeCardsContainer.css

- Fixing color contrasts acording to WCAG standards !
- Alt texts, aria labels for other elements too !

Color contrast changes

---

src/components/Footer.jsx

- **I have worked for #289 **
- **My pull request closes #289 **
---

Acessibility: close report modal with escape

---

src/pages/clubs/ClubsRegister.jsx
src/styles/UserLogin.css

- **I Ishaan have worked for 301**
- **My pull request closes #301 **
---

fix: #301- Labels for register club and minor updates

---

src/components/Navbar.jsx
src/styles/Navbar.css

- **I <your name here> have worked for #308**
- **My pull request closes #308**
---

fixed identification of active menu in navbar issue

---

src/components/Banner.jsx

- **I <your name here> have worked for #313 **
- **My pull request closes #313**
---

Changed banner button grammar

---

src/components/Footer.jsx

- **I vivek rawat have worked for #315**
- **My pull request closes #315**
---

Report modal data not cleared after submit/closed

---

cypress.config.js
cypress/.eslintrc.json
cypress/e2e/1-getting-started/todo.cy.js
cypress/e2e/2-advanced-examples/actions.cy.js
cypress/e2e/2-advanced-examples/aliasing.cy.js
cypress/e2e/2-advanced-examples/assertions.cy.js
cypress/e2e/2-advanced-examples/connectors.cy.js
cypress/e2e/2-advanced-examples/cookies.cy.js
cypress/e2e/2-advanced-examples/cypress_api.cy.js
cypress/e2e/2-advanced-examples/files.cy.js
cypress/e2e/2-advanced-examples/local_storage.cy.js
cypress/e2e/2-advanced-examples/location.cy.js
cypress/e2e/2-advanced-examples/misc.cy.js
cypress/e2e/2-advanced-examples/navigation.cy.js
cypress/e2e/2-advanced-examples/network_requests.cy.js
cypress/e2e/2-advanced-examples/querying.cy.js
cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
cypress/e2e/2-advanced-examples/traversal.cy.js
cypress/e2e/2-advanced-examples/utilities.cy.js
cypress/e2e/2-advanced-examples/viewport.cy.js
cypress/e2e/2-advanced-examples/waiting.cy.js
cypress/e2e/2-advanced-examples/window.cy.js
cypress/e2e/milan-tests/helloworld.cy.js
cypress/fixtures/example.json
cypress/support/commands.js
cypress/support/e2e.js
package-lock.json
package.json
test1.md

- New cypress tests
- Setting up Basic helloworld tests to visit milan page

feat : Added new cypress tests

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
.github/release-drafter.yml

- Added new issue labels
- Changed priorities of bugs to high
- Changed priorities of features to mid
- Updates on templates

New issue labels

---

src/styles/Navbar.css

- **I Ayush Raj have worked for #322 **
- **My pull request closes #322 **
---

Fix:Updated navlinks, Now changes color on hover

---

CONTRIBUTING.md
rules/FrontendSetup.md

- **I Arpit Verma have worked for #337 **
- **My pull request closes #337 **
Instead of simply showing up a broken link error, now the link goes to [rules](https://github.com/IAmTamal/Milan/tree/main/rules)
---

fix: Necessary changes were done to enhance Docs

---

README.md

The sentences have been corrected or rephrased and the License has been added to the end of the file.
- **I - Krupali have worked for 320**
**My pull request closes #320**
Before | After
------- | -------

fix: Changes in ReadMe + License Update

---

Dockerfile
docker-compose.yaml
server/Dockerfile
server/package.json

- **I <your name here> have worked for #343 <issue number>**
- **My pull request closes <hashtag issuenumber>**
---

Feature : Dockerize the web app 🛠

---

src/pages/ContactUs.jsx

* Accessibility : Highlighting errors in contact form  (#329)
- **I @MANUSRAO have worked for #329**
- **My pull request closes #329**
---

Accessibility : Highlighting errors in contact form 

---

src/pages/AboutUs.jsx
src/pages/ContactUs.jsx
src/pages/Donate.jsx
src/pages/display/ClubsPage.jsx
src/pages/display/EventsPage.jsx

- I Sneha Farkya have worked for #354 
- My pull request closes #354 
Code of About us page
About us page
Similarly, I have added footer to Contact, club and events page too.
Looking forward to see it as a valuable contribution 😄
---

fix: Added footer to each page

---

src/components/Footer.jsx

- **I @MANUSRAO  have worked for #362**
- **My pull request closes #362**
---

Updated footer to point to correct links

---

public/index.html
src/components/Footer.jsx
src/pages/user/UserRegister.jsx
src/styles/Footer.css
src/styles/index.css

Revert "Fix : Updates to textareas and copyrights 🛠"

---

src/components/Navbar.jsx
src/components/SocialIcons.jsx
src/styles/Footer.css

- **I @MANUSRAO  have worked for #330**
- **My pull request closes #330**
---

Adding contact button to footer and removing from navbar

---

src/pages/display/EventsPage.jsx
src/styles/EventsPage.css

- **I , Sutthinart Khunvadhana, have worked for #382**
- **My pull request closes #382**
---

fix: Events page mobile #382

---

src/pages/Donate.jsx
src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/clubs/EventCreate.jsx
src/pages/user/UserLogin.jsx
src/pages/user/UserRegister.jsx

Closes #378  
My PR closes #378 
I was told to modify toast ,add some feature and remove some feature from it.
I made necessary changes in toast in every file it was being used.
---
Hey @IAmTamal  I made the changes you mentioned , have a look.

Toast finally modified

---

src/styles/Footer.css

**My PR closes #398**
- Fix the alignment of social icons
- Reduce the dependency on hardcoded positional values
---
Here are the visible results of the fix
> ![fix-misalignment-social-icons](https://user-images.githubusercontent.com/73063553/194422852-f761d92c-7400-4ee6-a455-8482d63f1248.png)

[BUG FIX] Fixed the alignment of the social-btn

---

cypress.config.js
cypress/e2e/milan-tests/helloworld.cy.js

- Check header texts in homepage
- Check for all homepage buttons
- Check for Social icons

fix : added homepage tests for cypress

---

src/styles/Banner.css

My PR closes #407 
I was told to fix the responsiveness of the buttons of home page. 
I tried to fix the  responsiveness  by  modifying break  point which will make it responsive for maximum no of  devices.
- [✅] My code follows the code style of this project.
- [✅] This PR does not contain plagiarized content.
- [✅] The title and description of the PR is clear and explains the approach.

Home page button responsiveness 

---

src/pages/clubs/ClubsRegister.jsx
src/pages/user/UserRegister.jsx

**My PR closes #405**
Change the text inside Toast after registration to "Registered your account ! ".
Changed the text inside Toast after registration to "Registered your account ! ".
---

fix: Change in the text inside Toast after registering.

---

server/routes/User.js

**My PR closes #427**
Move the JWT secret key to .env file
Moved the JWT secret key to .env file
---

Fix: Moved JWT SECRET key to .env

---

server/routes/User.js
src/components/Loading/index.jsx
src/pages/display/ClubsPage.jsx
src/pages/display/EventsPage.jsx
src/styles/Loading.css

Closes
**My PR closes #425**
Add loader when data is being fetched from server on clubs page and events page
Created Reusable Loading Component
Add loader when data is being fetched from server on clubs page and events page
---

Added a new loader in Events page 🎉

---

src/components/Banners/Banner.jsx
src/styles/Banner.css

**My PR closes #423 **
Add a button with Minimal design to navigate back to top of the page only for the Home page
Added the button with the above functionalities
It only appears when you scroll on a bit on the page keeping the landing visual clean

Add back to top button on Home page

---

src/components/DonateUs.jsx
src/pages/Donate.jsx

**My PR closes #335**
I was supposed to make the donateus page login authenticated 
I created the new component for the donateus container [DonateUs] which will be rendered only if user/club is logged in, otherwise they will be redirected to the homeBanner asking them to login/register either as a Club or User !
---

fix-donate-page-auth-issue

---

package-lock.json
src/components/Banners/Banner.jsx
src/styles/Banner.css

Closes #438 
**My PR closes #438**
Changed the `Banner.css` file adding `background-attachment` property to fixed to `.banner-inner` class.
Landing Page background attachment UI change and setting it's height to 100vh
Changed the `Banner.css` file adding `background-attachment` property to fixed to `.banner-inner` class.
---
My change is more of a practical dynamic change. Although I am attaching the screenshot here as well as video link.
[Video Link](https://drive.google.com/file/d/1cb7FQijF9mbpsaZJbCkuj8liQBrlhMXw/view?usp=sharing)

fix: landing page background attachment

---

src/components/Banners/Banner.jsx
src/styles/Banner.css

**My PR closes #441 **
Change the Color of the Landing page buttons.
1. Changed the Colors of the buttons
2. Added subtle box shadow
3. Changed font to "Open Sans"
4. tweaked the padding

Landing Page "Continue As" Buttons Styling Tweak

---

src/components/Banners/Banner.jsx
src/styles/Banner.css

Closes #454 
**My PR closes #454**
Corrected the scroll to top button functionality
I added an `onClick` attrib on the button with class `up-btn` by implementing a callback that scroll to (0,0) (i.e. to the top of the page). Works correctly for both Desktop and Mobile 
---

fix: corrected scroll button functionality

---

cypress/e2e/milanTest.spec.js
package-lock.json
server/routes/Clubs.js
src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/user/UserLogin.jsx
src/pages/user/UserProfile.jsx
src/pages/user/UserRegister.jsx
src/service/MilanApi.js

- New tests for Cypress logins

DX : Added new cypress tests 🛠

---

src/components/Navbar/index.jsx

**My PR closes #464**
Correct the active state CSS for `Shop` route
The path name in class declaration was incomplete, I just completed the path `location.pathname === "/shops/shop"` like this.
---

fix: shop route active state CSS corrected

---

.eslintignore
.eslintrc.json
.husky/pre-commit
.husky/pre-push
.prettierignore
.prettierrc
package-lock.json
package.json
src/App.jsx

**My PR closes #458 **
Make use of husky and lint-staged to create a pre-commit or pre-push hooks to run linter and fix auto-fixable issues before a PR can be created
1. added `prettier`, `lint-staged` packages
2. Created `pre-push` and `pre-commit` hooks to run linter and formatter before code is pushed to remote repository
3. added `prettierignore` and `priettier` config file
4. created `eslint` config and `eslintignore` file
5. added linting and formatting scripts in `package.json`
---

Automated linting using pre-commit/pre-push hooks

---

cypress/e2e/milanTest.spec.js
package-lock.json
package.json
public/index.html
public/sitemap.txt
server/routes/Display.js
src/index.jsx
src/pages/ContactUs.jsx
src/pages/Donate.jsx
src/pages/Home.jsx
src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/shops/ShopLanding.jsx
src/pages/user/UserLogin.jsx
src/pages/user/UserRegister.jsx

- Helmet
- SEO (meta tags added)
- google's seo verification
- Cypress tests added

DX : Seo and Cypress tests 🛠

---

package-lock.json
src/components/Banners/Banner.jsx

**My PR closes #478**
To correct the scroll back to the top button behavior as it is visible even on the top of the page
I only added an `aos` attribute `data-aos-once="false"` enabling the animation repetition only for this button. Works well.
---

fix: scroll back to top button behavior resolved

---

package-lock.json
src/styles/Footer.css

My PR closes #492 
I was told to fix the  responsiveness  of the submit button for  bug report 
I tried to fix the  responsiveness of  the button ! 
---
- [✅] My code follows the code style of this project.
- [✅] This PR does not contain plagiarized content.
- [✅] The title and description of the PR is clear and explains the approach.

Sumbit button  responsiveness 

---

README.md

**My PR closes #494**
I was told to fix the README.md file so that all the links in the guideline section are usable.
I updated the file so that all the links work. See picture below 
---

fix: Update the guideline links

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml

**My PR closes #509**
- To add the default title for the bug PR template
- To add the option for the dropdown 
- Update the label of duplicate issue
- Added the default title for the bug PR template
- Added the option for the dropdown 
- Updated the label of duplicate issue
---

Updates in Issue templates

---

src/components/Footer/index.jsx
src/pages/display/ClubsPage.jsx
src/styles/ClubsPage.css
src/styles/Footer.css

**My PR closes #502 **
I was told to fix the issue of Club card overflowing at the bottom of the page. This was the issue screenshot ! 
I made some component changes and added a few div to contain the issue and changed 'postition' variant for them. I also had to change the padding and gapping for the card from % to px and eliminate auto calculation for all the responsive modes ! 
---

Fixes for card overflowing issue

---

src/components/Footer/index.jsx
src/styles/Footer.css

Added conditional rendering to the footer based on the device width.
**My PR closes #508**
- Hide the text "With Milan we aim at bringing all the various..." for mobiles.
- Replace it with the centered header "Check out our socials".
- Centre the social icons.
Added conditional rendering to the footer component in order to render either the header or paragraph, based on the current window width. I also centered the footer's social icons
- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.

Fix for footer in mobiles

---

server/index.js
server/routes/Clubs.js

**My PR closes #499 **
Due to some bug were not able to add new events .
Fixed the issue for adding new event . and fixed .env configs .
---

Fix for new events not created

---

src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/user/UserLogin.jsx
src/pages/user/UserRegister.jsx

**My PR closes #523 **
I stopped showing multiple toasts for login and register for both user and community
---

fix: duplicate toasts

---

src/App.jsx
src/pages/Donate.jsx
src/pages/display/EventsPage.jsx
src/styles/Donate.css

**My PR closes #517**
Make changes in Donate page according to #517
Make the Donate page title styling to be consistent with other pages.
Fixed overflow of cards and add space at the top and bottom. I reused the container class that is already used in "Clubs" page.
Added a loading spinner when cards are loading.
If the user has not logged in, redirect them to login page and show toast.
The ToastContainer has to be outside of the Router for the toast to show properly, so I added a ToastContainer in App.jsx.
---

Donate page styling

---

src/components/Events/SingleEvent.jsx
src/pages/display/EventsPage.jsx
src/styles/EventsPage.css

**My PR closes #513 **
I was asked to fix the overflowing issue of the event cards on the Event listing page !
I fixed the overflowing issue of the cards and changed the alignment of the cards as well to make it similar to my previously fixed Club page. I also the checked the responsiveness of these cards and it's working just fine on all the devices !
---

Fixed #513 > Event Card Issue !

---

src/styles/UserLogin.css

Issue : #491
Closes #491 
**My PR closes #491**
When the cursor hovers over the login button of the website, a black (dark colour) colour border around it will be shown so that the user can know that they are about to click a button.
Do the  same as above for all buttons
Did the same for login button
---
- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.

Minor changes to buttons

---

src/styles/ShopHeader.css

**My PR closes #525 **
Closes #525 
The issue was to make the shop page responsive for mobile devices:
1. have to remove the image in the header, in small screen devices.
2. Increase the width of an element to take more space, while in small screen devices.
1. for the first task, I have made the display none of the img element in shops page.
2.  for the second task, increased the width of the element, and increase the letter spacing.
---

fix bug shop page responsive

---

src/styles/ClubsPage.css

**My PR closes #544**
To fix the button alignment.
Changed the height of the card to 100%
---

fix: fixed event card button alignment

---

src/components/Banners/DonateBanner.jsx

**My PR closes #547 **
Added a condition to redirect the user to "/donateus" only if they are logged in otherwise redirect them to "/user/login" page.
---

Authentication check on Donations page

---

src/components/Cards/ProductsCard.jsx
src/styles/ProductsCard.css
src/styles/index.css

**My PR closes #550 
Make sure the products card are looking the same as the design that was provided by the UI/UX team.
modified the product card as per the figma design
---

Modify product cards design

---

src/App.jsx
src/pages/AboutUs.jsx
src/pages/ContactUs.jsx
src/pages/Donate.jsx
src/pages/Home.jsx

**My PR closes #558  **
Add footer in all the pages rather than just showing it on the homepage
Removed the Footer component from the homepage and a few other pages and added it in App.tsx so that it can render in all the pages
---

Fix: Added footer in all the pages

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
.github/labels.json
README.md

**My PR closes #567**
Hacktoberfest labels removed from issue templates
Removing extra labels from the issue templates
---

Hacktoberfest labels removed from issue templates

---

rules/FrontendSetup.md

**My PR closes #577 **
change the command of starting the app on localhost from npm start to npm run dev.
did the same
---

[DOCS] Starting on local host

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml

Closes #578 
Removed additional information from all issue template

Removed additional information from all issue template

---

src/components/Milaninfobanner.jsx
src/styles/Milaninfobanner.css

Making Milan's Home Page Responsive
Slight Change in JSX portion
Closes #589
**My PR closes #589 **
Home page responsiveness
Milan was working fine on Desktop and on mobile devices... 
Perhaps the only issue was in ipad devices 
I tried making it responsive.

Home page responsiveness

---

src/components/SingleClubEvent.jsx
src/pages/clubs/ClubDetails.jsx
src/styles/ClubDetails.css
src/styles/Donate.css

Closes #594 
-  To made the page responsive can use bootstrap grid system along with media queries
- To add tagline in place of address in clubs card
- To make the detailed club page mobile responsive as well (for all devices)
- Replaced address with tagline in clubs card
- Used bootstrap grid system along with media queries to make the detailed club page responsive for mobile, tab, and bigger screens
---
- Mobile View
(Before change)
(After change)

[FIX] : Made detailed club page responsive

---

src/styles/ClubDetails.css

Closes: #605
I have changed the design of the button so that is matches rest of the website and reduced the font size of club tagline as I think that it would look better if it is smaller. Also added hover effect to the button.
This is how it looked earlier.

refactor: refactor the button and tagline component in clubdetails.css 

---

index.html
src/components/Footer.jsx
src/components/Modal.jsx
src/styles/Footer.css
src/styles/Modal.module.css

Closes: #612 
- Created new component for modal as `Modal.jsx`
- Wrote css for modal component in `Modal.module.css`
- Created a portal which will in insert modal at `#modal` next to `#root` (not nested)
- Converted modal's border radius to `px` from `%` so we can have the same design independent of the modal's height and width

refactor: improved modal

---

.eslintrc.js
src/pages/user/UserRegister.jsx
src/utils/showToast.js

Closes: #618 
- In UserRegistration.jsx, 
- a missing import is added.
- the pin code is casted to number before sending it to the backend.
- In .eslintrc.js
- a property is added to avoid prop-type error from eslint
Additionally, I would like to mention that the documentation should be updated accordingly after adding new features ( e.g. pre-commit hooks, linting packages etc.) to avoid unexpected errors.

fix: sign up problem

---

CONTRIBUTING.md

docs: updated CONTRIBUTING.md

---

src/components/Milaninfobanner.jsx

Closes: #634
Set an explicit width and height on images elements to reduce layout shifts and improve CLS.

fix: adds explicit width and height to images

---

rules/CloneSetup.md

Closes: #660
Fixed the links to setting up frontend, backend , Docker.

docs: added links to repo setup page

---

cypress/e2e/milanTest.spec.js
src/components/Navbar.jsx

Closes: #667
This PR fixes the failing cypress test.

fix: failing cypress test

---

rules/BackendSetup.md
rules/CloneSetup.md

Closes: #665
- corrected variable names
-  added "setting up Razorpay keys"
Before
Now

docs: added proper variable names for razorpay documentation

---

src/components/Banners/Banner.jsx
src/components/Banners/DonateBanner.jsx
src/components/Button.jsx
src/components/Footer.jsx
src/components/Milaninfobanner.jsx
src/components/Navbar.jsx
src/components/SingleClubEvent.jsx
src/pages/Donate.jsx
src/pages/clubs/ClubDetails.jsx
src/pages/clubs/ClubForgotpassword.jsx
src/pages/clubs/ClubsLogin.jsx
src/pages/clubs/ClubsRegister.jsx
src/pages/display/EventsPage.jsx
src/pages/user/UserForgotpassword.jsx
src/pages/user/UserLogin.jsx
src/pages/user/UserRegister.jsx
src/styles/Banner.css
src/styles/Button.module.css
src/styles/ClubLogin.css
src/styles/ClubsPage.css
src/styles/Footer.css
src/styles/Milaninfobanner.css
src/styles/Navbar.css
src/styles/ShopLanding.css
src/styles/UserLogin.css

Closes: #644 
- Have created a custom `Button` component, with the following props:
- `variant`: `solid` (default) | `outline`
- `to`: null (default) - pass the `to` prop with url to use this button as a `Link`
- `size`: null (default) | `sm` - used in the navbar
- `...rest`: rest button props can be passed
- Replaced the buttons with the `Button` component
- Commented some unused code to avoid linting errors
**This is is just for previewing the button styles**

fix: custom button component to fix inconsistency

---

src/components/Navbar.jsx
src/context/MilanState.jsx
src/styles/Button.module.css
src/styles/Navbar.css

Closes: #699 
Hey have centered the links and added the sign in button , let me know 
Thanks

feat: added sign In button to navbar

---

src/components/Footer.jsx
src/styles/Footer.css

…it is added in the footer.css
Closes: #761 
Updated Footer CSS:
- Added an underline animation on hover for the footer links.
- To achieve this, a new CSS class "underlineanimation" has been added to the footer links.
- The "underlineanimation" class applies a CSS transition effect to create an animated underline on hover.
- The color of the underline animation is set to "#e26959" to match the desired style.
- The CSS code for the "underlineanimation" class has been added to the existing CSS file for the footer component.
- This change enhances the user experience by providing visual feedback when interacting with the footer links.

feat: updated the "here" link in the footer - issue#761 

---

src/components/Navbar.jsx
src/context/MilanState.jsx
src/utils/clickAwayListener.jsx

fix: navbar on mobile or smaller screens now get closed automatically on clicking outside of navbar
Closes: #759 
- created a clickaway listener component in `utils` folder.

fix: close navbar on clicking outside

---

index.html

Closes: #855 
Added primary meta tags, og tags, and twitter tags.

fix: meta tags added

---

src/styles/Banner.css
src/styles/ClubsPage.css
src/styles/Navbar.css
src/styles/ShopLanding.css

Closes: #774 
Added sticky nav bar

feat: added sticky navbar

---

src/pages/clubs/ClubDetails.jsx
src/service/MilanApi.js

Closes: #854 
Removed all the unnecessary console logs from the code.

fix: console log removed

---

server/index.js
src/components/Banners/Banner.jsx
src/components/Navbar.jsx
src/components/SingleClubEvent.jsx
src/pages/AboutUs.jsx
src/pages/display/ClubsPage.jsx
src/pages/display/EventsPage.jsx
src/pages/display/StatesData.js
src/styles/App.css
src/styles/Banner.css
src/styles/Button.module.css
src/styles/ClubsPage.css
src/styles/EventsPage.css
src/styles/Navbar.css
src/utils/filter.js

This PR is to test and merge a new feature with some additional changes.
Tagging @suzy-g38 to keep on loop.

feat: location based search (#852)

---

.github/dependabot.yml

Closes: #959 
- add field for a commit message
```yml
commit-message:
prefix: "chore(deps)"
```
- Add a field for the label `dependencies`, which I believe is the default, just in case you want to change it in the future.
```yml
labels:
- dependencies
```

docs: update dependabot workflow

---

src/pages/Home.jsx

Closes: #936 
I added the footer section on the homepage which was not visible priorly.
@tamalCodes Please review this issue and merge to the main branch. 

fix: added footer to homepage.

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug.yml
.github/dependabot.yml
src/pages/Home.jsx

Closes: #960
Updated checklist:
- add a non-mandatory field: `I am a GSSoC23 contributor`
- add link to check similar issue
> Image

docs: update checklist in all issue forms

---

.eslintrc.js
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
README.md
SECURITY.md
rules/DockerSetup.md
src/components/Banners/Banner.jsx
src/components/Footer.jsx
src/components/SocialIcons/index.jsx

Keeping @Anmol-Baranwal in the loop since their changes are included too.

fix: changes to issue forms and socials

---

src/components/Footer/Footer.jsx

Closes: #843 
I changed only the wrong URL in the footer section previously it was "/display/events" and "/shops/shop" You also see the below screenshot. The correct URL is "/events" and "/shop".
before
after

fix: added correct link on the footer section

---

src/components/Banners/Banner.css

Closes: #1023 
Added line-height:1 to heading

fix: 4 tagline irregularity in small size

---

src/components/Button/AuthButton/TopButton.jsx

closes #1054 
Go back button in sign in and register was going to previous page in the history stack, whereas only place it can go to is home page. 
So, fixed that issue and now its going to home page only.

fix: go back button return to home

---

src/hooks/useValidation.js
src/pages/Auth/AuthFormmodule.js
src/pages/Auth/AuthSignup.jsx
src/pages/Club/Details/ClubDetails.jsx

closes #1078
Added a field to input an email when registering a club. Added the website to the POST request so it will be functional when the backend gets updated accordingly. Added a link to the website on the clubs details page which is only visible when it exists.

feat: added website field to club registration and details page

---

src/components/Button/GlobalButton/Button.module.css

closes #1089 
Fixed the signup button border hover effect by changing the border pixel property.
border: #e26959 solid 2px;  - >   border: #e26959 solid 1px;
Before Changes:
After Changes:

fix: signup button border hover effect

---

src/pages/Event/AllEvents/Events.jsx

closes #1095 
I have comment some code in events page which was not currently in use and also create unnecessary api calls which resolve the Loading problem. However i just comment the code if in the future the requirement will occur then we can use that code.

fix: removed unnecessary api call from events page

---

src/components/Button/BacktoTop/BacktoTop.css

closes #1088 
removed the hover styles on the back-to-top button. The scroll-up button turned transparent when someone hovered over it which was causing issues on a dark background.

fix: remove hover effect on back to top button

---

src/hooks/useValidation.js
src/pages/Auth/AuthSignup.jsx

closes #1077 
Added an Iframe code input field for club registration with validation through the useValidation hook.

feat: added iframe code input field to club sign in

---

src/components/Cards/SingleClubEvent/SingleClubEvent.css
src/components/Cards/SingleClubEvent/SingleClubEvent.jsx
src/components/PageHeader/Header.jsx
src/pages/Club/AllClubs/Clubs.css
src/pages/Club/AllClubs/Clubs.jsx

closes #1105 
Use right elements to improve accessibility.

feat: improve clubs page accessibility

---

src/components/Banners/Banner.css
src/components/Banners/Milaninfobanner.jsx

I have **removed** the number **circles** from all sections of the website to create a **cleaner** and more **streamlined** design.
_before:_ 
_after:_
Kindly, label it as `hacktoberfest` and `hacktoberfest-accepted`. Thanks!

fix: remove number circles from homepage

---

README.md

closes #1145 
I have added a link leading to the definition of conventional Pull Request as mentioned by @tamalCodes

docs: added definition of conventional pr link

---

docs/DockerSetup.md

closes #1151 
Added a link that leads to the official docker desktop download center.

docs: added a link that leads to the official docker desktop downloading documentation

---

src/components/Banners/HomeBanner.jsx

closes #1150 
Fixed the typo of Tomorrow spelling in home screen

fix: typo fixed in the home page
